#!/usr/bin/env python

import os
import argparse
import subprocess
import yaml
import sys
from pathlib import Path

MAIN_CONFIG = Path("/etc/nff.yml")
INCLUDED_CONFIG = Path("/etc/nff.d")
SHARE_PATH = Path("/usr/share/nff")
NFT_CONFIG = Path("/etc/nftables.d/00-nff.nft")
VERBOSE = False

# Verbose logging function
def verbose(*msgs):
  if VERBOSE:
    print(*msgs)


# Configuration functions
def load_file(path):
  if not path.exists():
    print(f"Error finding file {path}", file=sys.stderr)
    sys.exit(1)
  try:
    with open(path, "r") as f:
      return yaml.safe_load(f) or {}
  except yaml.YAMLError as e:
    print(f"Error loading file {path}: {e}", file=sys.stderr)
    sys.exit(1)

def load_cfg():
  config = load_file(MAIN_CONFIG)
  if INCLUDED_CONFIG.is_dir():
    for extra in INCLUDED_CONFIG.glob("*.yml"):
      config.update(load_file(extra))
  return config

# Processing functions
def get_default_interface():
  try:
    result = subprocess.run(["ip", "route", "get", "8.8.8.8"], capture_output=True, text=True).stdout.split()
    return result[result.index('dev')+1] # Extract the interface name from the output
  except (subprocess.CalledProcessError, ValueError, IndexError):
    return "eth0" # Fallback to eth0 if we can't determine the default interface

def nff_to_nft(config):
  rules = {
    'exclusive': 'destroy table inet filter\n' if config.get('exclusive', True) else '\n'
  }

  for proto in ['tcp', 'udp']:
    for direction in ['in', 'out']:
      key = f"{proto}_{direction}"
      ports = config.get(proto, {}).get(direction, {}).get('allow', [])
      if ports:
        ports = ", ".join(map(str, ports))
        rules[key] = f"; elements = {{ {ports} }}"
      else:
        rules[key] = ''

  t_in = rules.get('tcp_in', set())
  t_out = rules.get('tcp_out', set())
  u_in = rules.get('udp_in', set())
  u_out = rules.get('udp_out', set())
  default_in = config.get('default-policies', {}).get('input', 'drop')
  default_out = config.get('default-policies', {}).get('output', 'accept')
  def_net_interface = get_default_interface()
  template = f"""#!/usr/bin/nft -f
# Generated by nff - edits will be overwritten
{rules['exclusive']}
destroy table inet nff
table inet nff {{
    set tcp_in {{
        type inet_service{t_in}
    }}
    set tcp_out {{
        type inet_service{t_out}
    }}
    set udp_in {{
        type inet_service{u_in}
    }}
    set udp_out {{
        type inet_service{u_out}
    }}

    chain input {{
      type filter hook input priority 0;
      policy {default_in};

      ct state invalid drop comment "Drop invalid packets"
      ct state {{established, related}} accept comment "Allow tracked connections"
      iif lo accept comment "Allow loopback traffic"
      ip protocol icmp icmp type echo-request limit rate 10/second accept comment "Allow ICMP requests with rate limit"
      limit rate 50/second burst 15 packets comment "Allow general traffic with rate limit, prevent DoS"
      tcp dport 22 meter brute_block {{ ip saddr timeout 1m limit rate 5/minute }} accept comment "Allow SSH with brute-force protection"
      pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited comment "Reject other host-directed traffic"
      counter
      
      tcp dport @tcp_in accept comment "Allow incoming TCP to allowed ports"
      udp dport @udp_in accept comment "Allow incoming UDP to allowed ports"
    }}

    chain output {{
      type filter hook output priority 0;
      policy {default_out};

      ct state invalid drop comment "Drop invalid packets"
      ct state {{established, related}} accept comment "Allow tracked connections"
      oif lo accept comment "Allow loopback traffic"

      tcp dport @tcp_out accept comment "Allow outgoing TCP to allowed ports"
      udp dport @udp_out accept comment "Allow outgoing UDP to allowed ports"
    }}

    chain forward {{
        type filter hook forward priority 0;
        policy drop;
    }}
}}
destroy table netdev nff
table netdev nff {{
    chain ingress_lockdown {{
        type filter hook ingress device "{def_net_interface}" priority -500;
        # Uncomment below to drop fragments (common in some DDoS attacks)
        #ip frag-off & 0x1fff != 0 drop
    }}
}}"""
  return template

# Singletons
def show_version():
  with open(SHARE_PATH / "version", 'r') as f:
    print(f.read().strip())

# Execution flag functions
def show_rules(config, args):
  if args.nfstyle:
    try:
      result = subprocess.run(["nft","list","ruleset"], capture_output=True, text=True)
      print(result.stdout)
    except FileNotFoundError:
      print("Error: nftables is not accessible. Check if it is installed and in the PATH", file=sys.stderr)
  else:
    # Print out the YAML config in a nice way
    print(config)

def apply_rules(config, args):
  new_config = nff_to_nft(config)
  if NFT_CONFIG.exists():
    verbose(f"Backing up existing config to {NFT_CONFIG}.bak")
    NFT_CONFIG.rename(NFT_CONFIG.with_suffix(".bak"))
    with open(NFT_CONFIG, "w") as f:
      f.write(new_config)
    verbose(f"Applying NFF rules...")
    subprocess.run(["nft","-f",str(NFT_CONFIG)], check=True)

  print(f"NFF rules generated and written to {NFT_CONFIG}")
  print("Would you like to apply these rules now? (Y/n)")
  response = input().strip().lower()
  if response in ['y', 'yes']:
    subprocess.run(["systemctl", "restart", "nftables"], check=True)
    print("NFF rules applied!")
  else:
    print("NFF rules not applied.")

def arg_parser():
  parser = argparse.ArgumentParser(description="nff: A simple nftables firewall tool")
  parser.add_argument('-V', '--verbose', action='store_true')
  parser.add_argument('-v', '--version', action='store_true')
  subparsers = parser.add_subparsers(dest="status | apply")

  # Show rules

  show_p = subparsers.add_parser('status')
  show_p.add_argument('-N', '--nfstyle', action='store_true')
  show_p.set_defaults(func=show_rules)

  # Apply Configs

  apply_p = subparsers.add_parser('apply')
  apply_p.set_defaults(func=apply_rules)

  return parser

def main():
  if os.geteuid() != 0:
    print("Error: nff must be run as root (use sudo).", file=sys.stderr)
    sys.exit(1)

  global VERBOSE
  parser = arg_parser()
  args = parser.parse_args()

  # Check verbosity
  if args.verbose:
    VERBOSE = True
  elif args.version:
    show_version()
    sys.exit(0)

  # Load configs and begin
  config = load_cfg()
  if hasattr(args, 'func'):
    args.func(config, args)
  else:
    print("Ran into an unknown error!", file=sys.stderr)
    sys.exit(1)

if __name__ == "__main__":
  main()
